apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql


    # Fd0I3lJ4ZX81v!ru*Ogj(3m%
    # viraat070000